server:
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    plugins:
      - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.0.1"
        repository: "https://maven.lavalink.dev/releases"
        snapshot: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    #ratelimit:
      #ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
      #excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
      #strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
      #searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
      #retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO

plugins:
  lavasrc:
    providers:
      # Pour Spotify
      spotify: false # Définir sur true si vous avez des identifiants Spotify
      spotifyClientId: "" # Votre ID client Spotify
      spotifyClientSecret: "" # Votre secret client Spotify
      
      # Pour Apple Music
      applemusic: false # Définir sur true si vous avez un token Apple Music
      appleMusicToken: "" # Votre token Apple Music
      appleMusicCountryCode: "US" # Code pays pour Apple Music
      
      # Pour Deezer
      deezer: true
      deezerSources:
        - "youtube"
      
      # Pour Yandex Music
      yandexmusic: false
      
      # Pour FlowerTube (YouTube sans API key)
      floweryoutube: true # Utilise YouTube sans API key
      
      # Sources à utiliser pour les recherches
      defaultSearchSources:
        - "youtube"
        - "deezer"
      
      # Sources à utiliser pour les recherches par défaut
      defaultTopSearchSources:
        - "youtube"
        - "deezer"
